### ISSUE TITLE
remark v5 API is async now

### ISSUE THREAD

**Issue by bebraw** [mapbox/mdast-react#20]
Hi,

Just thought to note that [remark](https://www.npmjs.com/package/remark) changed its API so that it's async. The signature is like this:

``` javascript
remark().use(lint).use(html).process('## Hello world!', function (err, file) {
    console.error(report(file));
    console.log(file.toString());
});
```

You might want to tweak the README example accordingly.

**Comment by wooorm** [comment]
@bebraw That’s not really true, it’s more that the return value is now a virtual file instead of a string / React element

The sync interface is still very much allowed / favoured often!

P.S. @tmcw I did quite a lot on sanitation in `remark-html`, which is now very virtual and very safe. Take a look at [the index.js](https://github.com/wooorm/remark-html/blob/da73b54acde5028ba5d874afb3714c079cdb2dae/index.js).

remark-react could use something a lot similar, with the exception of instead of stringifying to HTML ([L60](https://github.com/wooorm/remark-html/blob/da73b54acde5028ba5d874afb3714c079cdb2dae/index.js#L60)), going to react with [hast-to-hyperscript](https://github.com/wooorm/hast-to-hyperscript).

**Comment by bebraw** [comment]
@wooorm Ah, great to hear! I got misled by the README. Closing. 👍

**Comment by wooorm** [comment]
Abstract: so instead of `remark().use(react).process('## Hello world!')`, `remark().use(react).process('## Hello world!').contents` should be used.

@bebraw Whoops, sorry! If you have suggestions or concerns, could you raise them in the Gitter? I’d love to know about them.

**Comment by bebraw** [comment]
@wooorm I'm good for now.

I guess adding that `.contents` bit to the README would help. That bit me today and I ended up writing [html-webpack-remark-plugin](https://www.npmjs.com/package/html-webpack-remark-plugin) to deal with the async interface. No probs. 😄

**Comment by wooorm** [comment]
Ah, well the thing there is that it’s a bit weird that remark is “stringifying” to React. In essence, `toString` simply returns `file.contents`, so it would also work for React.

I’d rather not advertise accessing `.contents`. Maybe buffers will be added in the future, meaning people’s code will break if they use `.contents` instead of `.toString()`.

**Comment by sapegin** [comment]
@wooorm So what is preferred way? 

``` html
<div id='preview'>
  {remark().use(reactRenderer).process(this.state.text).contents}
</div>
```

or

``` html
<div id='preview'>
  {remark().use(reactRenderer).process(this.state.text).toString()}
</div>
```

I’d like to submit a pull request to fix non-working example in the Readme.

**Comment by wooorm** [comment]
~~The latter (`toString()`), as buffers are now also supported, and `toString()` automatically transforms those!~~ This is not the case for `remark-react`.

**Comment by wooorm** [comment]
Whoops, hold on, as this plugin exposes an AST, it should use `contents`. 😬
