### ISSUE TITLE
Produced DOM is bloated with react-text

### ISSUE THREAD

**Issue by vladshcherbin** [mapbox/mdast-react#39]
In the demo, if we use even simple `hey` element, DOM gets bloated with `react-text`.

<img width="575" alt="screen shot 2017-04-07 at 8 49 28 pm" src="https://cloud.githubusercontent.com/assets/6711845/24812723/efaca144-1bd3-11e7-8bb1-178bd2da4d2d.png">

It it possible to avoid this?

**Comment by medfreeman** [comment]
Hi,
it is a standard behavior of React v15.
In previous versions React used to wrap text nodes in additional `<span>` elements instead.
It is needed for React to have the ability to update 'individual pieces of text'.

More info [here](https://facebook.github.io/react/blog/2016/04/07/react-v15.html#no-more-extra-spans).

**Comment by wooorm** [comment]
That’s not bloat, as @medfreeman points out, it’s a feature to make updates more performant!

**Comment by vladshcherbin** [comment]
@medfreeman @wooorm yeah, but in this example `createElement` doesn't wrap text elements and the produced DOM is clean.

Example:

![screen shot 2017-05-13 at 1 24 26 pm](https://cloud.githubusercontent.com/assets/6711845/26024710/e29f710c-37df-11e7-89e6-0d2666e0b4d3.png)

[jsBin example link](https://jsbin.com/lizepofevi/edit?html,js,output)

Can remark-react work this way or am I missing something?

**Comment by wooorm** [comment]
Hmm, I have some ideas on this but I don’t know enough about React’s internals. Anyone with more experience with React that has opinions on this?

**Comment by quoeradem** [comment]
The jsBin that @VladShcherbin linked does not produce `react-text` because ES6 string interpolation is being used so that `React.createElement` is provided a single child element.

`React.createElement` wraps child elements in `react-text` when an array is passed into it's **children** arg (even if the array only contains 1 element). As far as I can tell, this behavior is only necessary when an element contains multiple children and has no positive impact on single-child elements.

Simply reducing the **children** array to a single value if it only contains a single element should avoid _most_ of unnecessary `react-text` comments.

**Comment by MoOx** [comment]
Those things are here because React server side API is used (to generate html, no just DOM manipulation). This is not an issue but anyway, this will go await with React 16.

**Comment by wooorm** [comment]
From reading all the comments here (thanks all!) I’m going to close this as I don’t think it’s a bug.

Feel free to comment below or PR something if you don’t think so.
