### ISSUE TITLE
Add Typescript types

### ISSUE THREAD

**Issue by alexkreidler** [mapbox/mdast-react#69]
A type definition file would be very helpful for those of us who us TS. Let me know if you're open to a PR for this.

Thanks for the project!

**Comment by wooorm** [comment]
We do accept type definitions! See [this list of PRs](https://github.com/search?q=add+types+is%3Apr+is%3Aclosed+user%3Awooorm+user%3Amdx-js+user%3Amicromark+user%3Aremarkjs+user%3Arehypejs+user%3Aretextjs+user%3Aunifiedjs+user%3Asyntax-tree+user%3Avfile+user%3Aget-alex+user%3Awords+-repo%3Asyntax-tree%2Fideas+-repo%3Aremarkjs%2Fideas+-repo%3Arehypejs%2Fideas+-repo%3Aretextjs%2Fideas+-repo%3Aunifiedjs%2Fideas+-repo%3Avfile%2Fideas+-author%3Aapp%2Frenovate+-author%3Aapp%2Fgreenkeeper+-author%3Aapp%2Fdependabot+-author%3Aapp%2Fdependabot-preview+-author%3Aapp%2Fpull&type=Issues) that have added types before!

**Comment by ChristianMurphy** [comment]
To add on, `remark-react` builds on and surfaces options from: https://github.com/syntax-tree/mdast-util-to-hast, https://github.com/syntax-tree/hast-util-sanitize, and https://github.com/syntax-tree/hast-to-hyperscript each of which have typings that can be imported/leveraged here.

**Comment by wooorm** [comment]
I’m going to close this issue because PRs that add types are accepted in all unified projects, and I don’t see much value in keeping issues open for a few, or all, of the projects without types.

Furthermore, I want to archive and deprecate this project, as the suggested route as noted in the readme is to use the parts in this project instead (which have types), but it’s confusing that both ways are possible.
